"""
Django settings for learnispire project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lbtp9=ydf=^(u(o4wo8+n8k)i&1ycpbfdrz)yaaipv-(68^$3t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "192.168.29.191",
    "localhost",
    "127.0.0.1",
    "172.17.21.14",
    "192.168.137.173",
    "*",
]
PAYU_CONFIG = {
    "MERCHANT_KEY": "8qyJJz",  # Replace with your PayU merchant key
    "MERCHANT_SALT": "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDcUwnxGLlT/H9o+QwaeLTK3khY0c8j9QwWXlPwo5ollCtnCzut5QppOL4/SlluMliFp09kvYIRagjDNnHPoCS5z6gdWUnjNez5E8TPaa3xXHUQdkZyg6IctnDLd56l+8WI3QQPXT4DYxH2ihvZyjwmVdJLBJIH6i24M8UftE3iklbjuUissMg8MW4jwkSBdYU38wykja/ThV5hvxnqDFDttvukmmeX5Oh67UeuvwIl8xgpXu9BeYzyJQZF1Rf84DhpHhkF3dndfglbAI6orFoiktNpNQzSpc+2OWlIcKsA4G4iJJ5nAysAGkQMzTzme1aI7pC730xAOyxOYOVfPX3AgMBAAECggEBAL1poU/tIZdyCmoyGyXciQr1V/jGubR1BEUzgcGOIew0uc33zQgx/LL7bUm4ORWvp+SbXBrfwfg0YgZOHwXdikhVOrnR7I4PDsH2Y7iXCGuUPIRkqN44mCsfe/KQEs0nUHxZMdPHbAQ3RRwhzwxgoynCwvhUcQdbP2y1pZwMaAF1G8YiFZSpWNlj+8G37QtzIW289VPbVWn6D442KzsTbgGpV1B/7mJt6Z+IBA34O32JYfTQwmPVPRIiYDtMfbPChjeBV7Xiqd1utyfE/f4IT6M0ubkmE88vfZHKiJIBcHYhjLDc2qdACoMhSinW6f8wKtQ+VdG8PAYKdIdgOEofxVkCgYEA/40qKyl+/wFcE0SR2DfuGHx8wimhRSnSijMPISdi5s/Dwl75AZDKwgwUIEqG2WPVZbEx1iiiC1nT7Gqa/GtDkZ0y0YZsDXcDZVX9cl/OpHRgDBF4e+EtikfPIhqbQ8pQUbzy5WZfnsr7CXAP07et0aajo/X/T/sWRiL6TdPZp9UCgYEAw8kfQMzZs5hcXZhfwCwqfsaWYlAJjZfKSWD5Yl66EURnZrr5l4HZZvezfli7FpKy8zaoUS6D+YSvBqBbEkluu40j/50P/z8Pm/IQ1STOx6y44EvM6frCH2AZDuwVq7cRn7EPzrrRub2/GIWucDL2NGQAUIiXC87yRSNZjxqm+JsCgYBfR8/IJgGerHAbEv7Zwgi5Ank1n3XspqpEMsNaVigO7LoNV4G57rVaYkyCuabLmOhwsP9m3OGGH+jfBeRhZtDbkuPmsRrKbmxKtSP5J/WQ5X8GIOFuNsfW/e0hxw/K17zYrP1XQLM4LnAo1aphAuQA/gOXV1npBTIJ1nLC39EQPQKBgFWlXKufMTjUVMuIxZIuf+R3gP++3X74QMB60H1MzP6Sut0AvACgB/d4Mif6LtWAFRI5/cWNoKP9fAddDJniT7Nx2aaPEZlp/60LZnunH2HP2AwefKR6UoMhKbUSZ6R3cBk4fp7DsM0dCURz7kwcrwFaIZ0ZM2IyBF9kSGBGm3YzAoGBAKh1PuaeqLCHg5OVavJD8ccm57dPgS007WD2EiUlylGH4nKsUbofjgeXX4SLZA0Ij/0z4fdlWGbrTiO8xk1Gz33e3VhfmLj/z4CiJMAoGGckifYTMki9i0R7Gn8dc1RJLJipE5DFhe6FjBI2gausLpBsZ9PQvCak1DWlDBiHiCK3",  # Replace with your PayU salt
    "MODE": "LIVE",  # TEST for testing, LIVE for production
    "SUCCESS_URL": "http://127.0.0.1:8000/",
    "FAILURE_URL": "http://127.0.0.1:8000/",
    "CANCEL_URL": "http://127.0.0.1:8000/",
    "TEST_URL": "https://test.payu.in/_payment",
    "LIVE_URL": "https://secure.payu.in/_payment",
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "landing.apps.LandingConfig",
    "accounts.apps.AccountsConfig",
    "student_dashboard.apps.StudentDashboardConfig",
    "teacher_dashboard.apps.TeacherDashboardConfig",
    "admin_dashboard.apps.AdminDashboardConfig",
    "scheduling.apps.SchedulingConfig",
    "payments.apps.PaymentsConfig",
    "communications.apps.CommunicationsConfig",
    "meetings.apps.MeetingsConfig",
    "common.apps.CommonConfig",
    "django.contrib.sites",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "learnispire.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "learnispire.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""
import dj_database_url

# Replace the DATABASES section of your settings.py with this
DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://neondb_owner:npg_t9crmibCFO3X@ep-hidden-leaf-a8ceibb4-pooler.eastus2.azure.neon.tech/neondb?sslmode=require",
        conn_max_age=600,
        ssl_require=True,
    )
}

# In settings.py
GOOGLE_SERVICE_ACCOUNT_FILE = "edulance-452011-f1970b2af93f.json"
GOOGLE_CALENDAR_ID = "admin@learnispire.com"  # Or your specific calendar ID
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

import os

SITE_ID = 1
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_ADAPTER = "accounts.adapters.CustomAccountAdapter"

# Login/logout URLs
LOGIN_REDIRECT_URL = "/accounts/login-redirect/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"

# Twilio credentials for WhatsApp
TWILIO_ACCOUNT_SID = "ACbddd51b0fd3a72e950ed4c641731aec3"
TWILIO_AUTH_TOKEN = "1a1350e26c9ad8cade6567177dd913aa"
TWILIO_WHATSAPP_FROM = "+15557325365"
ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm",
}
# PayU credentials
PAYU_MERCHANT_KEY = os.getenv("PAYU_MERCHANT_KEY")
PAYU_MERCHANT_SALT = os.getenv("PAYU_MERCHANT_SALT")
PAYU_MODE = os.getenv("PAYU_MODE", "test")  # 'test' or 'live'

# Google Meet API credentials
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID")

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = "sandeepvarada4@gmail.com"
EMAIL_HOST_PASSWORD = "bamw gang shif czxe"
DEFAULT_FROM_EMAIL = "sandeepvarada4@gmail.com"
